
name: Artifact

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: doscienario

jobs:
  Artifact:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Angular Application
        run: npm it && npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: doscenario-build
    # Publish `v1.2.3` tags as releases.
          path: dist/doscienario/
