name: Electron builder

on:
  push:
    branches:
      - master
    tags:
      - v*
  
jobs:
  Windows_Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14.13
    - name: install node tools
      run: npm install -D electron electron-builder typescript
    - name: Install dependencies
      run: npm install
    - name: Build on Windows
      run: npm run build
    - uses: actions/checkout@v2
      with: 
        repository: totodore/build-doscienario
        token: ${{ secrets.CR_PAT }}
    - name: Build Electron
      run: 
        ls;
        cd doscenario-build;
        npm it;
        tsc;
        cp -rf ../doscienario/dist/doscienario ./dist/;
        electron-builder build -w;
    - name: see directory
      run: ls ./build
    # - uses: lucyio/upload-to-release@master
      # with:
        # name: lucyio/electron
        # path: ./electron_dist/squirrel-windows
        # action: unpublished
        # release_id: 0.5.9
        # release-repo: lucyio/electron