name: Electron builder

on:
  push:
    tags:
      - v*
  
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - uses: actions/setup-node@master
      with:
        node-version: 14.13
    - name: install node tools
      run: npm install -g electron electron-builder typescript
    - uses: actions/checkout@v2
      with: 
        repository: totodore/build-doscienario
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    - name: Build Angular app
      run:
        ./build.ps1;
        npm install;
        tsc -b tsconfig.json;
        electron-builder build -w --publish=never;
        ls ./build;
    - name: Create Windows Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.branch_name.outputs.SOURCE_TAG }}/Windows
        title: ${{ steps.branch_name.outputs.SOURCE_TAG }} - Windows
        files: |
          ./build/*.exe
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/setup-node@master
        with:
          node-version: 14.13
      - name: install node tools
        run: npm install -g electron electron-builder typescript
      - uses: actions/checkout@v2
        with: 
          repository: totodore/build-doscienario
          token: ${{ secrets.CR_PAT }}
          submodules: recursive
      - name: Build Angular app
        run: 
          ./build.bash;
          npm install;
          tsc -b tsconfig.json;
          electron-builder build -l --publish=never;
          ls ./build;
      - name: Create Linux Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.branch_name.outputs.SOURCE_TAG }}/Linux
          title: ${{ steps.branch_name.outputs.SOURCE_TAG }} - Linux
          files: |
            ./build/*.AppImage