name: Electron builder

on:
  push:
    branches:
      - master
    tags:
      - v*
  
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@master
      with:
        node-version: 14.13
    - name: install node tools
      run: npm install -g electron electron-builder typescript
    - uses: actions/checkout@v2
      with: 
        path: build
        repository: totodore/build-doscienario
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    - name: Build Angular app
      run:
        env GH_TOKEN=${{ secrets.CR_PAT }};
        cd build;
        ./build.ps1;
        npm install;
        tsc -b tsconfig.json;
        electron-builder build -w;
        ls ./build;
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ./build/*.exe
        title: "${{ github.ref }} - Windows"
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 14.13
      - name: install node tools
        run: npm install -g electron electron-builder typescript
      - uses: actions/checkout@v2
        with: 
          path: build
          repository: totodore/build-doscienario
          token: ${{ secrets.CR_PAT }}
          submodules: recursive
      - name: Build Angular app
        run: 
          env GH_TOKEN=${{ secrets.CR_PAT }};
          cd build;
          ./build.bash;
          npm install;
          tsc -b tsconfig.json;
          electron-builder build -l;
          ls ./build;
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./build/*.exe
          title: "${{ github.ref }} - Linux"
      