name: Electron builder

on:
  push:
    branches:
      - master
    tags:
      - v*
  
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@master
      with:
        node-version: 14.13
    - name: install node tools
      run: npm install -D electron electron-builder typescript
    - uses: actions/checkout@v2
      with: 
        path: build
        repository: totodore/build-doscienario
        token: ${{ secrets.CR_PAT }}
    - name: Install dependencies
      run: npm install
    - name: Build Angular app
      run: 
        cd build; 
        ./build.ps1;
    - name: Build Electron app
      run: tsc -b tsconfig.json
    - name: Create Electron package
      run: electron-builder build -w
    - name: see directory
      run: ls ./build
    # - uses: lucyio/upload-to-release@master
      # with:
        # name: lucyio/electron
        # path: ./electron_dist/squirrel-windows
        # action: unpublished
        # release_id: 0.5.9
        # release-repo: lucyio/electron