name: Electron builder

on:
  push:
    tags:
      - v*
  
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@master
      with:
        node-version: 14.13
    - name: install node tools
      run: npm install -g electron electron-builder typescript
    - uses: actions/checkout@v2
      with: 
        repository: totodore/build-doscienario
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    - name: Build Angular app
      run:
        ./build.ps1;
        npm install;
        tsc -b tsconfig.json;
        electron-builder build -w --publish=never;
        ls ./build;
    - name: Create Release Windows
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ./build/build/*.exe
        tag: ${{ github.ref }}
        release: "${{ github.ref }} - Windows"
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 14.13
      - name: install node tools
        run: npm install -g electron electron-builder typescript
      - uses: actions/checkout@v2
        with: 
          repository: totodore/build-doscienario
          token: ${{ secrets.CR_PAT }}
          submodules: recursive
      - name: Build Angular app
        run: 
          ./build.bash;
          npm install;
          tsc -b tsconfig.json;
          electron-builder build -l --publish=never;
          ls ./build;
      - name: Create Release Linux
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./build/*.AppImage
          tag: ${{ github.ref }}
          release: "${{ github.ref }} - Linux"
      