
name: Artifact

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: doscienario

jobs:
  Artifact:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Angular Application
        run: npm it && npm run build

      - name: Deploy Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CR_PAT }}
          publish_dir: ./dist/doscienario
